export const ROUTE = {
  WELCOME: "Welcome",
  HOME: "Home",
  ITEM_LIST_CATEGORIES: "ItemListCategories",
  SHOP_DETAIL: "ShopDetail",
  CART: "Cart",
  ORDERS: "Orders",
  LOGIN: "Login",
  SIGN_UP: "SignUp",
  MY_PROFILE: "MyProfile",
  IMAGE_SELECTOR: "ImageSelector",
  LOCATION_SELECTOR: "LocationSelector",
  MY_LOCATION: "MyLocation",
  MAIN: "Main",
  AUTH: "Auth",
};
